#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     ,              tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     ,              tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//
// Single joystick control over left and right motors

//    Y-Axis determines robot speed and direction.
//       +127    full speed "forward"
//          0    stopped.
//       -128    full speed "reverse".
//
//    X-Axis determines steering
//        -128   turn left with left motor same speed as right but in opposite direction
//         -64   turn left with left motor stopped.
//           0   straight line. Both motors at same speed.
//         +64   turn right with right motor stopped.
//        +127   turn right with right motor same speed as left but in opposite direction
//
#include "JoystickDriver.c"

task main()
{
  while (true)
  {
    getJoystickSettings(joystick); // Get current joystick settings
    int joyY = joystick.joy1_y1;
    int joyX = joystick.joy1_x1;

    if (joyX > -10 && joyX < 10 && joyY > -10 && joyY < 10) {
    	motor[motorD] = 0;
    	motor[motorE] = 0;
    } else if (joyX < -10 && joyY < 10 && joyY > -10) {
    	short motorPower = -joyX / 127;
    	motor[motorD] = motorPower * 100;
    	motor[motorE] = motorPower * 100;
    } else if (joyX > 10 && joyY < 10 && joyY > -10) {
    	short motorPower = joyX / 127;
    	motor[motorD] = -(motorPower * 100);
    	motor[motorE] = -(motorPower * 100);
    }

    /*if (joyY > 120) {
    	motor[motorD] = -100;
    	motor[motorE] = 100;
    } else if (joyY < -120) {
    	motor[motorD] = 100;
    	motor[motorE] = -100;
  	} else if (joyX > 120) {
  		motor[motorD] = -100;
  		motor[motorE] = -100;
  	} else if (joyX < -120) {
  		motor[motorD] = 100;
  		motor[motorE] = 100;
  	} else {
  		motor[motorD] = 0;
  		motor[motorE] = 0;
  	}*/

    /*if (nDirection < 0)
    {
	    // Turn left

    	motor[motorD] = nMotorPower; // use power settings from Y-axis
    	motor[motorE] = nMotorPower * (64 + nDirection) / 64;
    }
    else
    {
	    // Turn right

    	motor[motorD] = nMotorPower; // use power settings from Y-axis
    	motor[motorE] = nMotorPower * (64 - nDirection) / 64;
    }*/
  }
}
